# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AdrLint < Formula
  desc "Automatically validates code changes against Architecture Decision Records using Claude."
  homepage "https://github.com/wbern/adr-lint"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wbern/adr-lint/releases/download/v0.1.0/adr-lint_0.1.0_macos_x86_64.tar.gz"
      sha256 "cb2a78a74be64969346bda89569a089c8cf87ef645d47a3d612f5addfae6e869"

      define_method(:install) do
        bin.install "adr-lint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wbern/adr-lint/releases/download/v0.1.0/adr-lint_0.1.0_macos_arm64.tar.gz"
      sha256 "22749d8e2c9cf4227b0f6f894e40e810e5695849bcf62ae95b0032bc5d61228b"

      define_method(:install) do
        bin.install "adr-lint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wbern/adr-lint/releases/download/v0.1.0/adr-lint_0.1.0_linux_x86_64.tar.gz"
      sha256 "1814bde59736a5df5a375fff11c08e0c31b7619433bb4f9a78e9945e18170d51"
      define_method(:install) do
        bin.install "adr-lint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wbern/adr-lint/releases/download/v0.1.0/adr-lint_0.1.0_linux_arm64.tar.gz"
      sha256 "a2886b6304c8d2c3ae1400ae10e018aea6117b2c061e8fbc990b1f32cec67e6f"
      define_method(:install) do
        bin.install "adr-lint"
      end
    end
  end

  test do
    system "#{bin}/adr-lint", "version"
  end
end
