# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AdrLint < Formula
  desc "Automatically validates code changes against Architecture Decision Records using Claude."
  homepage "https://github.com/wbern/adr-lint"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wbern/adr-lint/releases/download/v0.1.1/adr-lint_0.1.1_macos_x86_64.tar.gz"
      sha256 "25d1585b32b23f2fc0eb74077dbce77e4b37ad41dc2372862a49ac9b2378eb82"

      define_method(:install) do
        bin.install "adr-lint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wbern/adr-lint/releases/download/v0.1.1/adr-lint_0.1.1_macos_arm64.tar.gz"
      sha256 "8950b3a46e0394f8cfdea6b164e007c770f3da0eedfe836aa78fd1eb73580b8a"

      define_method(:install) do
        bin.install "adr-lint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wbern/adr-lint/releases/download/v0.1.1/adr-lint_0.1.1_linux_x86_64.tar.gz"
      sha256 "72719ad6dc7c5b3ff4fa4fb0757dbf2021f02dcd60acff335a62e8f62275f510"
      define_method(:install) do
        bin.install "adr-lint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wbern/adr-lint/releases/download/v0.1.1/adr-lint_0.1.1_linux_arm64.tar.gz"
      sha256 "7cc5f9932d22222c852393c791dc25852df74ab40cf86d97a50a7ebe7423c42a"
      define_method(:install) do
        bin.install "adr-lint"
      end
    end
  end

  test do
    system "#{bin}/adr-lint", "version"
  end
end
